spring.datasource.url=${DB_URL:jdbc:mysql://localhost}/dls
spring.datasource.username=dls
spring.datasource.password=dls
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql: true
