version: "3.8"
services:
  mysql:
    image: mysql:8.1.0
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-sublock}"
      - "MYSQL_USER=${MYSQL_USER:-sublock}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-sublock}"
    networks: 
      - my-shared-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD:-root} --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 30s
      retries: 30
      start_period: 30s
  sublock:
    image: dls.sublock:0.0.1
    environment:
      - DB_DRIVER=${DB_DRIVER:-com.mysql.cj.jdbc.Driver}
      - DB_URL=${DB_URL:-jdbc:mysql://mysql:3306/sublock}
      - DB_USERNAME=${MYSQL_USER:-sublock}
      - DB_PASSWORD=${MYSQL_PASSWORD:-sublock}
      - DB_PLATFORM=${DB_PLATFORM:-org.hibernate.dialect.MySQLDialect}
    networks: 
      - my-shared-network
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

networks:
  my-shared-network: {}
